# Site settings
title: Yuan Jiang - uTAS2016 Dublin
email: jiangyuan@tju.edu.cn
description: > # This webpage is mainly build for supplementary information download and
  Q&A section of Yuan's microTAS 2016 poster presentation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: yuanjiang
github_username:  crisone

# Build settings
markdown: kramdown
